### ISSUE TITLE
Game crashed while trying to chain grab Fox with Marth

### ISSUE THREAD

**Issue by KevinDigital** [schmooblidon/meleelight#6]

**Comment by schmooblidon** [comment]
I believe this was caused by grabbing the Fox on the first frame he techs the floor. Intangibility is supposed to activate immediately, but I went about it a weird way. I give it a timer, then after the action state code in the physics code I check the timer is > 0 then give the intangibility.

But a tech is initiated after both the initial action state code and this intangibility check, so it puts the timer on, but the actual intangibility won't run till the next frame. By then fox is grabbed and is intangible. If you throw him fast enough, a hit will be sent to the executeHits function which will only puts a victim into hitstun if they are tangible. So the throw runs but fox never gets put into hitstun, so the only thing it knows what to do is carry on the THROWN action, but those extra frames don't exist and it crashes.

This should now be fixed :)
